"""add market models

Revision ID: db3f7dd07f87
Revises: df71cf1a560d
Create Date: 2026-05-07 13:02:01.933516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db3f7dd07f87'
down_revision: Union[str, Sequence[str], None] = 'df71cf1a560d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crypto_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crypto_assets_symbol'), 'crypto_assets', ['symbol'], unique=True)
    op.create_table('market_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume_24h', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('price_change_percent_24h', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('high_24h', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low_24h', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quote_volume', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['crypto_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_snapshots_symbol'), 'market_snapshots', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_snapshots_timestamp'), 'market_snapshots', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_snapshots_timestamp'), table_name='market_snapshots')
    op.drop_index(op.f('ix_market_snapshots_symbol'), table_name='market_snapshots')
    op.drop_table('market_snapshots')
    op.drop_index(op.f('ix_crypto_assets_symbol'), table_name='crypto_assets')
    op.drop_table('crypto_assets')
    # ### end Alembic commands ###
